### ISSUE TITLE
Shouldn't this repo be called 'pyansys-templates'

### ISSUE THREAD

**Issue by germa89** [ansys/ansys-templates#115]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I dont know, I think it should be called 'pyansys-templates'

### 📝 Steps to reproduce

N/A

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
N/A
```

**Comment by RobPasMue** [comment]
I agree... Honestly, we have a huge chaos with names. I would either:
* Change its location to the `ansys` org
* Change its name to `pyansys-templates`

**Comment by greschd** [comment]
> Change its location to the ansys org

I'd prefer that option, since presumably one could also add e.g. C++ templates here. And some of the templates `ace-` are not really pyansys specific.

**Comment by akaszynski** [comment]
Agreed regarding the move to `ansys` org. @jorgepiloto, let me know if you want to take care of that or want me to.

**Comment by RobPasMue** [comment]
I can also handle it @jorgepiloto if you have any doubts (done it before). Ping me if you need any help.

**Comment by jorgepiloto** [comment]
Moving this repo to [Ansys](https://github.com/ansys/) org 🚀

**Comment by jorgepiloto** [comment]
Solved!
