### ISSUE TITLE
Change domain name from pyansys.com to ansys.com

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-templates#117]
Now that we have moved it to the @ansys org, we should modify the CNAME. This involves opening a ServiceNow ticket with IT

**Comment by jorgepiloto** [comment]
Thanks for opening this. I agree the domain should move now to "templates.ansys.com".

**Comment by RobPasMue** [comment]
Just created it by the IT team. Proceeding to adapt the project Settings
