### ISSUE TITLE
Issues templates no longer available

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-templates#119]
Due to the change of org, we have lost the issues templates available at PyAnsys. Do we want to keep them for this repo? If that's the case we should create a local copy for this repo..

Pinging @jorgepiloto for discussion. If we decide to do that, I can take care of it, no problem.

**Comment by jorgepiloto** [comment]
Good catch, @RobPasMue. Sure, let us use the issue templates. Those turned out to be very useful for new contributors and users reporting bugs.
