### ISSUE TITLE
Tox returns missing Python interpreter while Python is installed

### ISSUE THREAD

**Issue by iazehaf** [ansys/ansys-templates#126]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Tox returns SKIPPED: InterpreterNotFound when running these commands:

- tox -e doc
- tox -e syle

### 📝 Steps to reproduce

- git clone https://github.com/Solution-Applications/solutions-app-em-nvh-mapper.git
- python -m venv .venv
- .venv\Scripts\Activate.ps1
- python -m pip install -U pip poetry tox
- python -m pip install -r requirements/requirements_build.txt
- python -m pip install -r requirements/requirements_doc.txt
- python -m pip install -r requirements/requirements_tests.txt
- poetry run python -m pip install dist/ansys_solutions_em_nvh_mapper-0.1.dev0-py3-none-any.whl
- tox -e doc
- tox -e style

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
alabaster==0.7.12
ansys-sphinx-theme==0.4.2
atomicwrites==1.4.1
attrs==21.4.0
Babel==2.10.3
beautifulsoup4==4.11.1
bleach==5.0.1
build==0.8.0
CacheControl==0.12.11
cachy==0.3.0
certifi==2022.6.15
charset-normalizer==2.1.0
cleo==0.8.1
clikit==0.6.2
colorama==0.4.5
commonmark==0.9.1
coverage==6.4.1
crashtest==0.3.1
distlib==0.3.5
docutils==0.18.1
filelock==3.7.1
html5lib==1.1
idna==3.3
imagesize==1.4.1
importlib-metadata==4.12.0
iniconfig==1.1.1
Jinja2==3.1.2
keyring==23.7.0
lockfile==0.12.2
MarkupSafe==2.1.1
msgpack==1.0.4
numpydoc==1.4.0
packaging==20.9
pastel==0.2.1
pep517==0.12.0
pexpect==4.8.0
pkginfo==1.8.3
platformdirs==2.5.2
pluggy==1.0.0
poetry==1.1.14
poetry-core==1.0.8
ptyprocess==0.7.0
py==1.11.0
pydata-sphinx-theme==0.9.0
Pygments==2.12.0
pylev==1.4.0
pyparsing==3.0.9
pytest==7.1.2
pytest-cov==3.0.0
pytz==2022.1
pywin32-ctypes==0.2.0
readme-renderer==35.0
requests==2.28.1
requests-toolbelt==0.9.1
rfc3986==2.0.0
rich==12.5.1
shellingham==1.4.0
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.3.2.post1
Sphinx==5.0.2
sphinx-copybutton==0.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.1
tox==3.25.1
twine==4.0.1
urllib3==1.26.10
virtualenv==20.15.1
webencodings==0.5.1
zipp==3.8.1
```

**Comment by jorgepiloto** [comment]
Thanks for opening this @iazehaf. Investigating this... 🔎

**Comment by jorgepiloto** [comment]
I confirm that I can reproduce this locally.

**Comment by jorgepiloto** [comment]
The issue comes from a bad syntax in the `tox.ini` file:

```diff
-    py: python3{style,reformat}: python3
+    py: python3
+    {style,reformat,doc}: python3
```

**Comment by jorgepiloto** [comment]
This is a bug, see the demo branch for Poetry https://github.com/ansys/ansys-templates/blob/demo/pyansys-advanced-poetry/tox.ini

**Comment by jorgepiloto** [comment]
This is caused by the Jinja syntax. Fixing this in a couple of hours.

**Comment by iazehaf** [comment]
@jorgepiloto  thank you very much for your quick support. It works well!
