### ISSUE TITLE
Bug located in README.rst

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [ansys/ansys-templates#139]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The hyperlink is invalid ```https://templates.pyansys.com/```
This is on line 48 of Readme.rst

### 📝 Steps to reproduce

Select the [hyperlink](https://templates.pyansys.com/).

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
This is a documentation error and not related to Python code.
```

**Comment by jorgepiloto** [comment]
Good catch, @dcrawforAtAnsys! Thanks for opening this, let me fix it.
