### ISSUE TITLE
Add authors.md / maintainers.md

### ISSUE THREAD

**Issue by jacobevansgit** [ansys/ansys-templates#260]
### 📝 Description of the feature

Given the need to know of who is responsible for the repository, templates should include an `authors.md` or `maintainers.md` so appropriate contact can be made. 

### 💡 Steps for implementing the feature

Add to each template as best practice. 

### 🔗 Useful links and references

solution-templates has one itself. However the solutions do not.

**Comment by RobPasMue** [comment]
@jorgepiloto - let's reuse this issue to implement https://github.com/ansys/pygeometry/pull/561 in the templates
