### ISSUE TITLE
`pydocstyle` missing configuration for numpydoc convention

### ISSUE THREAD

**Issue by raph-luc** [ansys/ansys-templates#476]
Currently in repos based on `ansys-templates`, the numpydoc docstring checks take place only when building the docs. I believe `pydocstyle` should be configured out of the box for the numpydoc convention as well, otherwise it is unable to identify when docstrings don't follow the PyAnsys enforced style. This renders `pydocstyle` mostly useless in my understanding.

I am aware of two ways to do that, following [PyAnsys doc style guide](https://dev.docs.pyansys.com/doc-style/formatting-tools.html#the-pydocstyle-tool), can add this to `pyproject.toml`:
```
[tool.pydocstyle]
convention = "numpy"
```

or add this to `.pre-commit-config.yaml` in the last lines of the `pydocstyle` block:
```
args:
  - --convention=numpy
```

As discussed @RobPasMue

**Comment by RobPasMue** [comment]
@ansys/pyansys-core could somebody handle this implementation?

**Comment by Revathyvenugopal162** [comment]
@RobPasMue i can add this.

**Comment by RobPasMue** [comment]
Awesome @Revathyvenugopal162 - thanks for handling it
